// <auto-generated />
using System;
using AirWatch.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirWatch.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirWatch.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<double>("R0Mq135")
                        .HasDefaultValue(76630.0)
                        .HasColumnType("double precision");

                    b.Property<double>("R0Mq3")
                        .HasDefaultValue(25000.0)
                        .HasColumnType("double precision");

                    b.Property<double>("R0Mq5")
                        .HasDefaultValue(105000.0)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("RlMq135")
                        .HasDefaultValue(10000.0)
                        .HasColumnType("double precision");

                    b.Property<double>("RlMq3")
                        .HasDefaultValue(10000.0)
                        .HasColumnType("double precision");

                    b.Property<double>("RlMq5")
                        .HasDefaultValue(10000.0)
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mq135Adc")
                        .HasColumnType("integer");

                    b.Property<int>("Mq3Adc")
                        .HasColumnType("integer");

                    b.Property<int>("Mq5Adc")
                        .HasColumnType("integer");

                    b.Property<double>("PpmAlcohol")
                        .HasColumnType("double precision");

                    b.Property<double>("PpmCo2")
                        .HasColumnType("double precision");

                    b.Property<double>("PpmLpg")
                        .HasColumnType("double precision");

                    b.Property<double>("PpmNh3")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Timestamp");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.SensorCoefficient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AlertMax")
                        .HasColumnType("double precision");

                    b.Property<double>("CoefA")
                        .HasColumnType("double precision");

                    b.Property<double>("CoefB")
                        .HasColumnType("double precision");

                    b.Property<string>("GasTarget")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("GoodMax")
                        .HasColumnType("double precision");

                    b.Property<double>("SafeMax")
                        .HasColumnType("double precision");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("SensorType", "GasTarget")
                        .IsUnique();

                    b.ToTable("sensor_coefficients", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Device", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("AirWatch.Domain.Entities.Device", "Device")
                        .WithMany("Measurements")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AirWatch.Domain.Entities.Device", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
